### ISSUE TITLE
[T6] Misguided instructions for configuration

### ISSUE THREAD

**Issue by juhyun167** [dothat-ku/dothat#1]
I am wondering that there exists some misguided README.md instructions on your repository.
Please let me be informed if I were wrong.

- Installing `php7.0-fpm` needs additional repository to be added to APT package manager.
- You did not mention how to change the default PostgreSQL password.
- On nginx configuration, the root directory should be `[Clonded Folder]/dothat`, not `[Cloned Folder]`.
- Additional package `php-pgsql` should be installed to connect PostgreSQL from PHP. Otherwise, PHP would fail to call the function `pg_connect()`.
- Meanwhile, you recommended to use Ubuntu. Since there are already updated versions of PHP installed on recent Ubuntu distributions, installation of `php-pgsql` creates `pdo_pgsql.so` file on the folder that is not registered as proper extension directory for the PHP. Hence, the call to `pg_connect()` eventually fails.
- Therefore, you should inform the precise version of your testing environment, such as Ubuntu and PHP versions and additional package you have used or provide some Virtual Machines.

**Comment by dothat-ku** [comment]
Misguided README.md instructions has been changed!

**Comment by gnujchung** [comment]
Commit ID: 559b76b
Misguided README
Explanation: The README has been updated with more detailed instructions to follow as suggested. More instructions on how to change PostgresSQL password and PHP installation guide
