### ISSUE TITLE
[T6] First Attack

### ISSUE THREAD

**Issue by juhyun167** [dothat-ku/dothat#2]
**Environment**
- Lubuntu 18.04.2 LTS
- Nginx 1.14.0
- PHP 7.2.24

**Location**
Login and Signup form on `index.php`

**Type of Vulnerability**
Improper Input Validation ([CWE-20](https://cwe.mitre.org/data/definitions/20.html))

**Explanation**
The application is validating inputs through Javascript functions named `mailchar`, `namechar`, etc. Since there is no additional checking procedures like Regex matching on the server-side logic, it could be simply bypassed by disabling related functions in Javascript console on browsers. Also, the attacker can send the form with not-intended data using proxy filters like Burp Suite.

**Comment by dothat-ku** [comment]
Currently, `mailchar`, `namechar` functions stands for UI only and does not support security issues. However, back-end functions clean up each input from user or URL requests.

**Comment by juhyun167** [comment]
I am wondering which back-end functions you are mentioning. I see functions like `trim`, `stripslashes` now, but they were added just an hour ago. At the time Git-based CTF started there was only `pg_escape_string` function on your `load.php` for input sanitization, and that function could not filter XSS string since it only changes single quote to double quotes. Please check your commit history about the back-end cleanse functions and let me be informed if I were wrong.

**Comment by dothat-ku** [comment]
You are right but there was!

**Comment by juhyun167** [comment]
Does it mean that there were actually filtering procedures for XSS payloads at commit `4ac9dbe` on Nov 22, 2019?

**Comment by dothat-ku** [comment]
It mean there wasn't XSS filtering function.

**Comment by gnujchung** [comment]
Commit ID: 1ea38b1
Cause of Vulnerability: No input checking procedure on server-side logic
Explanation: Addition of functions in server-side logic to prevent any malicious input by users
