### ISSUE TITLE
[T6] Third Attack

### ISSUE THREAD

**Issue by juhyun167** [dothat-ku/dothat#4]
**Environment**
- Lubuntu 18.04.2 LTS
- Nginx 1.14.0
- PHP 7.2.24

**Location**
- `$_SESSION['username'] = $username;` on `load.php`, line 113
- `<?php echo $_SESSION['username']; ?>` on `index.php`, line 35

**Type of Vulnerability**
Improper Neutralization of Input During Web Page Generation ([CWE-79](https://cwe.mitre.org/data/definitions/79.html))

**Explanation**
During Signup procedure, the input value `$username` is sanitized through fuction `pg_escape_string`. Since the function only substitutes the the single quote character to double quote, malicious input containing XSS payloads can bypass this check. Then the value is copied to the session variable `$_SESSION['username']`, which is exposed directly on `index.php`, line 35.

**Contribution**
Jinseok Park for inspirations.

**Comment by dothat-ku** [comment]
bug fixed - malicious input containing XSS payloads can be cleaned up for bypass preventing.

**Comment by gnujchung** [comment]
Commit ID: 1ea38b1
Cause of Vulnerability: Improper Neutralization of Input
Explanation: Neutralizing functions have been updated so that XSS payloads cannot be bypassed
